#!/usr/bin/env bash
# Every local #include in the assembled engine must resolve to a file on disk,
# and every C++ TU the build compiles must parse.
#
# The sync copies the kalsallama tree through explicit copy lists
# (copy_llama_api / copy_common / copy_mtmd in scripts/sync-kalsallama.sh).
# Those lists do not learn: when the fork adds a file and an existing source
# starts including it, the file is simply absent and the NDK fails ~5 minutes
# into the APK build, far from the commit that caused it. That is how
#   common/peg-parser.h:3:10: fatal error: 'json.h' file not found
# reached CI on 2026-09-17 -- json.h/json.cpp, plus llama-kv-cache-dsa-iswa,
# llama-kv-cache-msa and llama-memory-hybrid-idx, all existed in the fork and
# none were on the lists.
#
# The scan below resolves every local `#include "..."` in seconds; the syntax
# pass then parses the C++ TUs the build actually compiles (host clang cannot
# codegen for ARM, but -fsyntax-only resolves declarations -- exactly the API
# drift the file scan cannot see, e.g. common_context_seq_rm going static).
# Conditional backend includes (CUDA, Vulkan, ...) and build-generated headers
# are listed as known-absent; anything else is a missing copy-list entry.
# The rn-owned sources need the app repo's bmoe headers: without
# KALSA_BMOE_DIR they are skipped and the gate only passes as PARTIAL
# (KALSA_ALLOW_PARTIAL_GATE=1) -- verify refuses half coverage otherwise.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPP="${1:-$ROOT/cpp}"
[ -d "$CPP" ] || { echo "[includes] missing $CPP -- run pin first" >&2; exit 1; }

python3 - "$CPP" <<'PY'
import os, re, sys, glob

cpp = sys.argv[1]
os.chdir(cpp)

# Absent for a reason: guarded by #ifdef for a backend we never build,
# emitted by the build, or living outside this repo.
KNOWN_ABSENT = {
    "ggml-cann.h", "ggml-cuda.h", "ggml-et.h", "ggml-openvino.h", "ggml-rpc.h",
    "ggml-sycl.h", "ggml-virtgpu.h", "ggml-vulkan.h", "ggml-webgpu.h",
    "ggml-zdnn.h", "ggml-zendnn.h",
    "llama-version.h",          # generated by the build
    "bmoe_stream.h",            # lives in the app repo (native/bmoe/rn);
                                # included unconditionally by rn-llama.cpp
    "sheredom/subprocess.h",    # mtmd-helper.cpp, behind #ifdef MTMD_VIDEO
    "windows.h",                # ggml-cpu.c, behind #if defined(_WIN32)
    "unistd.h",                 # quoted POSIX header, ggml-hexagon/htp-drv.h
    "htp-ops.h", "htp_iface.h",  # Hexagon SDK headers (HTP builds use Docker)
    "kleidiai/kleidiai.h",      # optional CPU backend, build-flag guarded
    "llamafile/sgemm.h",        # optional CPU backend, build-flag guarded
    "spacemit/ime.h",           # optional CPU backend, build-flag guarded
}
SEARCH = ["", "common", "common/jinja", "ggml-cpu", "tools/mtmd", "nlohmann"]

files = []
for pat in ("*.h", "*.cpp",
            "common/*.h", "common/*.cpp",
            "common/jinja/*.h", "common/jinja/*.cpp",
            "models/*.cpp", "models/*.h",
            "ggml-cpu/*.c", "ggml-cpu/*.cpp", "ggml-cpu/*.h", "ggml-cpu/*/*.cpp",
            "ggml-metal/*", "ggml-hexagon/*.cpp", "ggml-hexagon/*.h",
            "jsi/*.h", "jsi/*.cpp",
            "tools/mtmd/*.h", "tools/mtmd/*.cpp",
            "tools/mtmd/models/*.cpp"):
    files += [f for f in glob.glob(pat) if os.path.isfile(f)]

missing = {}
for f in files:
    with open(f, errors="ignore") as fh:
        body = fh.read()
    for m in re.finditer(r'^\s*#\s*include\s+"([^"]+)"', body, re.M):
        inc = m.group(1)
        if inc in KNOWN_ABSENT:
            continue
        here = os.path.join(os.path.dirname(f), inc)
        if os.path.exists(here) or any(os.path.exists(os.path.join(d, inc)) for d in SEARCH):
            continue
        missing.setdefault(inc, []).append(f)

if missing:
    print(f"[includes] FAIL: {len(missing)} unresolved include(s) in {cpp}")
    for inc, users in sorted(missing.items()):
        print(f"  {inc}  <- {', '.join(sorted(users)[:4])}")
    print("[includes] add the file to the copy lists in scripts/sync-kalsallama.sh,")
    print("[includes] then: scripts/sync-kalsallama.sh pin <sha>")
    raise SystemExit(1)

print(f"[includes] OK: every local include in {len(files)} files resolves")
PY

# rn-*.cpp include the bmoe stream port headers, which live in the app repo;
# point KALSA_BMOE_DIR at them to bring the rn-owned sources into the syntax
# pass. Without it (or without clang++) the pass runs PARTIAL and the gate
# only succeeds with KALSA_ALLOW_PARTIAL_GATE=1.
syntax_check() {
  local f="$1" extra="${2:-}"
  clang++ -std=c++17 -fsyntax-only \
    -I "$CPP" -I "$CPP/common" -I "$CPP/common/jinja" \
    -I "$CPP/ggml-cpu" -I "$CPP/tools/mtmd" \
    ${extra:+-I "$extra"} \
    "$f" > /tmp/kalsa-syntax.log 2>&1
}

partial=""
if ! command -v clang++ >/dev/null 2>&1; then
  partial="no clang++"
elif [ -z "${KALSA_BMOE_DIR:-}" ]; then
  partial="KALSA_BMOE_DIR not set (rn-*.cpp skipped)"
fi
if [ -n "$partial" ]; then
  echo "[includes] NOTE: partial syntax pass ($partial)"
fi

# C++ TUs only; the ggml C sources are covered by the include scan.
parse_group() {  # parse_group <extra-include-or-empty> <files...>
  local extra="$1"; shift
  local f
  for f in "$@"; do
    [ -f "$f" ] || continue
    if ! syntax_check "$f" "$extra"; then
      echo "[includes] SYNTAX FAIL: $(basename "$f")"
      grep -E "error:" /tmp/kalsa-syntax.log | head -3 | sed 's/^/    /' || true
      fails=$((fails + 1))
      continue
    fi
    case "$f" in
      "$CPP"/common/*) c_common=$((c_common + 1)) ;;
      "$CPP"/models/*) c_models=$((c_models + 1)) ;;
      "$CPP"/tools/mtmd/*) c_mtmd=$((c_mtmd + 1)) ;;
      "$CPP"/rn-*) c_rn=$((c_rn + 1)) ;;
    esac
  done
}

fails=0
c_common=0; c_mtmd=0; c_models=0; c_rn=0
parse_group "" "$CPP"/common/*.cpp "$CPP"/tools/mtmd/*.cpp \
  "$CPP"/models/*.cpp "$CPP"/tools/mtmd/models/*.cpp
if [ -z "$partial" ]; then
  parse_group "$KALSA_BMOE_DIR" "$CPP"/rn-*.cpp
fi

if [ "$fails" -gt 0 ]; then
  echo "[includes] $fails source(s) do not parse against $CPP."
  echo "[includes] An API the fork moved, or a header the sync did not bring."
  exit 1
fi
if [ -n "$partial" ] && [ "${KALSA_ALLOW_PARTIAL_GATE:-}" != "1" ]; then
  echo "[includes] FAIL: partial syntax pass ($partial)." >&2
  echo "[includes] set KALSA_BMOE_DIR=<app repo>/native/bmoe/rn, or KALSA_ALLOW_PARTIAL_GATE=1 to accept half coverage" >&2
  exit 1
fi
if [ -n "$partial" ]; then
  echo "[includes] OK (PARTIAL: $partial): $c_common common + $c_mtmd mtmd + $c_models models + $c_rn rn TUs parse"
else
  echo "[includes] OK: $c_common common + $c_mtmd mtmd + $c_models models + $c_rn rn TUs parse"
fi
