#!/usr/bin/env bash
# Every local #include in cpp/ must resolve to a file on disk.
#
# The sync copies the kalsallama tree through explicit copy lists
# (copy_llama_api / copy_common / copy_mtmd in scripts/sync-kalsallama.sh).
# Those lists do not learn: when the fork adds a file and an existing source
# starts including it, the file is simply absent and the NDK fails ~5 minutes
# into the APK build, far from the commit that caused it. That is how
#   common/peg-parser.h:3:10: fatal error: 'json.h' file not found
# reached CI on 2026-09-17 -- json.h/json.cpp, plus llama-kv-cache-dsa-iswa,
# llama-kv-cache-msa and llama-memory-hybrid-idx, all existed in the fork and
# none were on the lists.
#
# This gate runs in seconds and fails at the point of assembly instead,
# naming the missing file and its includers. Conditional backend includes
# (CUDA, Vulkan, ...) and build-generated headers are listed as known-absent;
# anything else is a missing copy-list entry.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPP="$ROOT/cpp"
[ -d "$CPP" ] || { echo "[includes] missing $CPP -- run pin first" >&2; exit 1; }

python3 - "$CPP" <<'PY'
import os, re, sys, glob

cpp = sys.argv[1]
os.chdir(cpp)

# Guarded by #ifdef for a backend we never build, or emitted by the build.
KNOWN_ABSENT = {
    "ggml-cann.h", "ggml-cuda.h", "ggml-et.h", "ggml-openvino.h", "ggml-rpc.h",
    "ggml-sycl.h", "ggml-virtgpu.h", "ggml-vulkan.h", "ggml-webgpu.h",
    "ggml-zdnn.h", "ggml-zendnn.h",
    "llama-version.h",          # generated by the build
    "bmoe_stream.h",            # MoE stream port, guarded
    "sheredom/subprocess.h",    # mtmd-helper.cpp, behind #ifdef MTMD_VIDEO
}
SEARCH = ["", "common", "common/jinja", "tools/mtmd", "nlohmann"]

files = []
for pat in ("*.h", "*.cpp", "common/*.h", "common/*.cpp",
            "common/jinja/*.h", "common/jinja/*.cpp",
            "jsi/*.h", "jsi/*.cpp", "tools/mtmd/*.h", "tools/mtmd/*.cpp"):
    files += glob.glob(pat)

missing = {}
for f in files:
    with open(f, errors="ignore") as fh:
        body = fh.read()
    for m in re.finditer(r'^\s*#\s*include\s+"([^"]+)"', body, re.M):
        inc = m.group(1)
        if inc in KNOWN_ABSENT:
            continue
        here = os.path.join(os.path.dirname(f), inc)
        if os.path.exists(here) or any(os.path.exists(os.path.join(d, inc)) for d in SEARCH):
            continue
        missing.setdefault(inc, []).append(f)

if missing:
    print(f"[includes] FAIL: {len(missing)} unresolved include(s) in cpp/")
    for inc, users in sorted(missing.items()):
        print(f"  {inc}  <- {', '.join(sorted(users)[:4])}")
    print("[includes] add the file to the copy lists in scripts/sync-kalsallama.sh,")
    print("[includes] then: scripts/sync-kalsallama.sh pin <sha>")
    raise SystemExit(1)

print(f"[includes] OK: every local include in {len(files)} files resolves")
PY
