#!/bin/bash
# Container-side half of scripts/build-htp-skels.sh; not runnable standalone.
#
# Runs inside ghcr.io/snapdragon-toolchain/arm64-android:v0.7 (Hexagon SDK
# 6.6.0.0, tools 19.0.07). /kalsa/src.tar is a git archive of the binding
# repo's vendored engine tree; /artifacts receives the four skels, the per-DSP
# logs, and the QAIC host stub pair. The repo checkout is never bind-mounted.
set -u

# Fixed extraction path: the compiler bakes it into the binaries (FARF takes
# __FILE__), so every build from this recipe carries the same prefix and the
# in-repo suffix (vendor/llama.cpp/...) in its strings. /tmp is the one path
# a non-root container user can rely on being writable.
SRC=/tmp/kalsa-htp/src
ART=/artifacts

rm -rf /tmp/kalsa-htp
mkdir -p "$SRC" "$ART"
tar -x -C "$SRC" -f /kalsa/src.tar
echo "ARCHIVE EXTRACT EXIT=$?"

HTP_SRC="$SRC/vendor/llama.cpp/ggml/src/ggml-hexagon/htp"
cd "$HTP_SRC" || exit 1

# The engine identity, linked into every skel: assert-htp-skels.sh reads
# KALSA_HTP_ENGINE=<full sha> out of each shipped .so, so a rebuild is the
# only way to make the binary name its engine - editing any text file cannot
# satisfy the gate. The TU is generated into the archive copy; the engine
# tree itself (repo or vendored) is never edited. The driver exports the sha
# from vendor/VERSIONS LLAMA_CPP_COMMIT.
: "${KALSA_HTP_ENGINE_SHA:?driver must export KALSA_HTP_ENGINE_SHA}"
if ! printf '%s' "$KALSA_HTP_ENGINE_SHA" | grep -qE '^[0-9a-f]{40}$'; then
    echo "KALSA_HTP_ENGINE_SHA='$KALSA_HTP_ENGINE_SHA' is not a full 40-hex sha" >&2
    exit 1
fi
printf '/* Generated by scripts/htp-skels-container.sh; not engine source. */\nconst char kalsa_htp_engine_stamp[] __attribute__((used)) =\n    "KALSA_HTP_ENGINE=%s";\n' "$KALSA_HTP_ENGINE_SHA" > "$HTP_SRC/kalsa_htp_stamp.c"
printf '\n# Kalsa: the shipped .so names its engine (read by scripts/assert-htp-skels.sh).\ntarget_sources(${HTP_LIB} PRIVATE kalsa_htp_stamp.c)\n' >> "$HTP_SRC/CMakeLists.txt"

export DEFAULT_HLOS_ARCH="${DEFAULT_HLOS_ARCH:-64}"
export DEFAULT_TOOLS_VARIANT="${DEFAULT_TOOLS_VARIANT:-toolv19}"
export DEFAULT_NO_QURT_INC="${DEFAULT_NO_QURT_INC:-0}"
: "${HEXAGON_SDK_ROOT:?image env missing HEXAGON_SDK_ROOT}"
: "${HEXAGON_TOOLS_ROOT:?image env missing HEXAGON_TOOLS_ROOT}"

overall_rc=0
for v in v73 v75 v79 v81; do
    build_dir="/tmp/kalsa-htp/build-$v"
    mkdir -p "$build_dir"
    cd "$build_dir"

    cmake "$HTP_SRC" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="$HTP_SRC/cmake-toolchain.cmake" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_LIBDIR="$ART" \
        -DHEXAGON_SDK_ROOT="$HEXAGON_SDK_ROOT" \
        -DHEXAGON_TOOLS_ROOT="$HEXAGON_TOOLS_ROOT" \
        -DDSP_VERSION="$v" \
        -DPREBUILT_LIB_DIR="toolv19_$v" \
        -DHEXAGON_HTP_DEBUG=OFF \
        > "$ART/conf-$v.log" 2>&1
    conf_rc=$?
    echo "CONF $v EXIT=$conf_rc"
    if [ "$conf_rc" -ne 0 ]; then
        overall_rc=1
        continue
    fi

    # The QNX-side DSP compiler occasionally fails to claim its license slot
    # under emulation; a clean re-run of the same build dir has always
    # succeeded. Three attempts, then give up so the driver fails loudly.
    build_rc=1
    for attempt in 1 2 3; do
        cmake --build . --config Release > "$ART/build-$v-attempt-$attempt.log" 2>&1
        build_rc=$?
        echo "BUILD $v ATTEMPT $attempt EXIT=$build_rc"
        if [ "$build_rc" -eq 0 ]; then break; fi
    done
    if [ "$build_rc" -ne 0 ]; then
        overall_rc=1
        continue
    fi

    cmake --install . > "$ART/install-$v.log" 2>&1
    echo "INSTALL $v EXIT=$?"
done

# The Android host build compiles the v73 QAIC stub; ship the pair beside the
# skels so the driver can refresh the tracked copy in htp/v73/. Copy from the
# build dir only: the committed stubs also live in the archive, and shipping
# those would mask a stub that no longer matches the IDL.
for f in htp_iface.h htp_iface_stub.c; do
    cp "/tmp/kalsa-htp/build-v73/$f" "$ART/" || { echo "missing QAIC output /tmp/kalsa-htp/build-v73/$f" >&2; overall_rc=1; }
done

echo "=== sha256 ==="
sha256sum "$ART"/libggml-htp-*.so 2>/dev/null
echo "=== versions ==="
echo "SDK: $HEXAGON_SDK_ROOT"
"$HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang --version" 2>/dev/null | head -1
echo "SCRIPT DONE overall_rc=$overall_rc"
exit "$overall_rc"
